### ISSUE TITLE
Error related to "raw potential" series

### ISSUE THREAD

**Issue by KennethNielsen** [ScottSoren/pyCOox_public#3]
Dear Scott

I received the following error report from a customer that attempted to re-run one of the publication scripts in this repository. As discussed on Slack, whether to fix this or not is basically up to a policy about whether to keep publication repositories up to date with new ixdat version or not.

The error is detailed in the attached document.

[error tutorial script.docx](https://github.com/ScottSoren/pyCOox_public/files/11797293/error.tutorial.script.docx)

I seem to remember that there was some work done, which changed somehow the names of some of the series, so it might just be that. If you don't have the bandwidth, but can point me in the right direction I so a PR for it.

**Comment by ScottSoren** [comment]
Hi Kenneth,

Thanks for passing on this problem. I've fixed it the repository here: https://github.com/ScottSoren/pyCOox_public/commit/0f40902d53129e5bf7916196e7b798d8b1490c6f

I think the policy should be that it is up to the publication repository owner (in this case me) to specify which version of ixdat it works with and, if they have time and their readers want it, update it to the newest version of ixdat. I don't think that can be the responsibility of ixdat developers (nor SI). On the other hand, ixdat / SI should be responsible for the tutorials on their own documentation... I guess the ixdat documentation should avoid recommending as tutorials repositories which aren't maintained :P

**Comment by ScottSoren** [comment]
But also, this was a failure at some point in ixdat - I've aimed for back-compatibility within the 0.2.x versions, and failed at some point in a minor way. 0.x.x. comes with no guarantee, but have to be better at this in the future...

Thanks a lot to whoever pointed this out!

**Comment by KennethNielsen** [comment]
> I think the policy should be that it is up to the publication repository owner (in this case me) to specify which version of ixdat it works with and, if they have time and their readers want it, update it to the newest version of ixdat. I don't think that can be the responsibility of ixdat developers (nor SI). On the other hand, ixdat / SI should be responsible for the tutorials on their own documentation... I guess the ixdat documentation should avoid recommending as tutorials repositories which aren't maintained :P

Completely agree on all accounts. Probably we should encourage owners of this sort of repository to list the supported ixdat version prominently on the README.

> But also, this was a failure at some point in ixdat - I've aimed for back-compatibility within the 0.2.x versions, and failed at some point in a minor way. 0.x.x. comes with no guarantee, but have to be better at this in the future...

That happens

> Thanks a lot to whoever pointed this out!

I will pass it on. Since I'm new to this kind or issue process, I forgot to ask permission to share the identity, I only asked for permission to share the report :(

**Comment by ScottSoren** [comment]
Thanks, and agreed!
I just updated the ixdat version in the README accordingly. Resolving this now :). Do send them my way if there are any more problems with this repo!
